#!/bin/bash

echo 'Start install Grunt.'

sudo npm install &&
sudo npm install -g grunt-cli &&
sudo npm install grunt-contrib-concat --save-dev &&
sudo npm install grunt-contrib-uglify --save-dev &&
sudo npm install grunt-contrib-watch --save-dev

echo 'Finish install Grunt.'